### ISSUE TITLE
element-ui 升级到2.12.0

### ISSUE THREAD

**Issue by JE-lee** [FEMessage/element#4]
**Describe the solution you'd like**
我希望能用element-ui 2.12.0才有的Drawer组件，因为项目中使用的element-ui theme是该项目的theme（基于2.4.1版本的element-ui），所以会导致.../drawer.css 找不到。

![image](https://user-images.githubusercontent.com/19794813/67929248-d45efe80-fbf7-11e9-99be-8189e973edf6.png)

**Comment by JE-lee** [comment]
已经通过
```javascript
import Drawer from 'element-ui/lib/drawer'
import 'element-ui/lib/theme-chalk/drawer.css'
```
避开了babel-plugin-compoent

**Comment by levy9527** [comment]
👍不过你提得有道理，需要考虑一波升级，这里主要的工作量是主题的重新定制，以及一些组件的兼容性测试。
